
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dayni
 */
public class lista extends javax.swing.JFrame {

    /**
     * Creates new form lista
     */
    public lista() {
        initComponents();
        this.setLocationRelativeTo(null);
        color.setBackground(Color.CYAN);

        cbociudad.addItem("QUITO");
        cbociudad.addItem("GUAYAQUIL");
        cbociudad.addItem("LATACUNGA");
        cbociudad.addItem("MANTA");
        cbociudad.addItem("CUENCA");
        cbociudad.addItem("ESMERALDAS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbociudad = new javax.swing.JComboBox<>();
        txt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        color = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbociudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbociudadItemStateChanged(evt);
            }
        });
        getContentPane().add(cbociudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 73, 129, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 116, 241, 115));

        jLabel1.setText("CIUDAD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 73, 94, 20));
        getContentPane().add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbociudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbociudadItemStateChanged
        String ciudad = (String) cbociudad.getSelectedItem();
        if (ciudad.equals("QUITO")) {
            txt1.setText("La capital de Ecuador");

        }
        if (ciudad.equals("GUAYAQUIL")) {
            txt1.setText("Es muy Grande");
        }

        if (ciudad.equals("LATACUNGA")) {
            txt1.setText("Mucho frio");
        }
        if (ciudad.equals("MANTA")) {
            txt1.setText("Comida deliciosa");
        }
        if (ciudad.equals("CUENCA")) {
            txt1.setText("Ciudad linda");
        }
        if (ciudad.equals("ESMERALDAS")) {
            txt1.setText("Tierra Verde");
        }
    }//GEN-LAST:event_cbociudadItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbociudad;
    private javax.swing.JButton color;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
